# Generated by Django 4.2.5 on 2023-11-28 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_instances', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='pilots_reminder_is_sent',
            field=models.BooleanField(default=False),
        ),
    ]
